const cardsData = [
    { name: 'Card 1', category: 'veterinaria', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-1.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/que-estudia-medicina-veterinaria", "_self")'>¿Qué estudia la medicina veterinaria?</h3><p>Conoce cómo esta carrera te prepara para proteger a los animales y su entorno. Estamos listos para orientarte y ayudarte a construir tu futuro profesional.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 2', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-2.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/cayetano-heredia-carreras", "_self")'>Carreras de Cayetano Heredia: 20 programas de excelencia</h3><p>¿No sabes qué estudiar? Conoce las 20 carreras de Cayetano Heredia que incluyen las áreas de gestión, ingeniería, educación, ciencias y salud.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 3', category: 'psicologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-3.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/en-que-consiste-carrera-psicologia", "_self")'>¿En qué consiste la carrera de psicología y cuánto dura?</h3><p>Descubre aquí en qué consiste la carrera de psicología y sus especialidades como psicología clínica, psicología organizacional, educativa y social.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 4', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-4.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/examen-admision-cayetano-heredia", "_self")'>Examen de Admisión de Cayetano Heredia: sigue estos pasos</h3><p>Encuentra la información que necesitas para rendir el examen de admisión de Cayetano Heredia: montos, documentos, temario, consejos y más.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 5', category: 'industrial', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-5.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/de-que-trata-ingenieria-industrial", "_self")'>¿De qué trata la carrera de ingeniería industrial y por qué elegirla?</h3><p>Conoce aquí de qué trata la carrera de ingeniería industrial, la malla curricular, duración y por qué elegir la carrera.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 6', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-6.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>17</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/matricula-cayetano-heredia", "_self")'>¿Cómo es el proceso de matrícula en Cayetano Heredia?</h3><p>Conoce cada paso del proceso de matrícula y comienza tu camino profesional en Cayetano.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 7', category: 'biologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-7.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/que-estudia-biologia", "_self")'>¿Qué estudia la biología?: ramas, historia e importancia</h3><p>Al descubrir qué estudia la biología, sabrás si esta carrera es para ti. Conoce su definición, ramas, historia e importancia.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 8', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-8.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/cayetano-heredia-sedes", "_self")'>Sedes de Cayetano Heredia: descubre todos los campus</h3><p>Las sedes de Cayetano Heredia están diseñadas para desarrollar tu potencial al máximo en un entorno que combina aprendizaje, convivencia y bienestar.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 9', category: 'enfermeria', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-9.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/en-que-consiste-carrera-enfermeria", "_self")'>¿En qué consiste la carrera de enfermería?</h3><p>Descubre aquí en qué consiste la carrera de enfermería, duración, competencias y por qué elegirla como carrera universitaria.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 10', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-10.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/cayetano-heredia-mensualidad", "_self")'>¿Cuánto es la mensualidad en Cayetano Heredia?</h3><p>Conoce la mensualidad de nuestras carreras de excelencia para una educación de calidad.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 11', category: 'veterinaria', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-11.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/cuanto-dura-la-carrera-veterinaria", "_self")'>¿Cuánto dura la carrera de veterinaria y zootecnia?</h3><p>Si buscas una carrera que combine el cuidado animal y compromiso ambiental, en Cayetano recibirás una formación integral alineada a tus metas.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 12', category: 'psicologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-12.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>18</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/cuanto-dura-carrera-psicologia", "_self")'>¿Cuánto dura la carrera de psicología y sus ventajas?</h3><p>Descubre aquí cuánto dura la carrera de psicología, su importancia, qué tan difícil es la carrera y las ventajas de estudiarla.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 13', category: 'industrial', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-13.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/malla-curricular-ingenieria-industrial", "_self")'>Malla curricular de ingeniería industrial y su campo laboral</h3><p>La malla curricular de Ingeniería Industrial te permite especializarte en diversas áreas, siendo una de las carreras más demandadas del mercado laboral.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 14', category: 'biologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-14.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/malla-curricular-biologia", "_self")'>Malla curricular de Biología: conoce los cursos de esta carrera</h3><p>La malla curricular de Biología está diseñada para ofrecerte una formación integral, combinando teoría y práctica desde el inicio de tu carrera.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 15', category: 'veterinaria', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-15.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/donde-puedo-estudiar-medicina-veterinaria", "_self")'>¿Dónde estudiar medicina veterinaria y zootecnia?</h3><p>Encuentra dónde estudiar Medicina veterinaria y zootecnia, descubre la mejor opcion y aspectos clave para desarrollar tu pasión por el cuidado animal.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 16', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-16.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/carreras-mejor-pagada", "_self")'>Carreras mejor pagadas 2024: lista actualizada</h3><p>Si aún no decides qué carrera estudiar, revisa esta lista y descubre cuáles son las 15 carreras mejor pagadas en Perú y dónde estudiarlas.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 17', category: 'psicologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-17.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/donde-estudiar-carrera-psicologia", "_self")'>¿Dónde estudiar la carrera de psicología en Perú?</h3><p>Elegir dónde estudiar la carrera de psicología es una decisión crucial, ya que será el primer paso en tu camino profesional.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 18', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-18.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>19</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/que-es-tercio-superior", "_self")'>¿Qué es el tercio superior?</h3><p>Descubre que es el tercio superior y sus beneficios para el inicio de tu carrera profesional.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 19', category: 'industrial', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-19.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/donde-estudiar-ingenieria-industrial", "_self")'>¿Dónde estudiar ingeniería industrial en Perú? [2025]</h3><p>Si te preguntas dónde estudiar Ingeniería Industrial, tu mejor opción es Cayetano Heredia. Descubre las herramientas y oportunidades que te ofrecemos.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 20', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-20.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/todo-sobre-la-excelencia-academica", "_self")'>Excelencia académica</h3><p>.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 21', category: 'biologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-21.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/donde-estudiar-biologia", "_self")'>¿Dónde estudiar Biología?</h3><p>.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 22', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-22.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/como-adaptarse-a-la-universidad", "_self")'>¿Cómo adaptarse a la universidad?</h3><p>Conoce los puntos clave que debes tener en cuenta antes de ingresar a la universidad.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 23', category: 'enfermeria', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-23.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/donde-estudiar-enfermeria", "_self")'>¿Dónde estudiar enfermería en Perú?</h3><p>Descubre dónde estudiar la carrera de enfermería en Perú teniendo en cuenta aspectos importantes para tomar la mejor decisión.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 24', category: 'otros', content: `<div class="bloque2DesktopCardsItem"><img src="https://blogs.cayetano.edu.pe/img/image-nota-24.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>20</h3><h3>|</h3><h3>12</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/bioincuba", "_self")'>¿Qué es Bioincuba? Incubadora de negocios de Cayetano</h3><p>¿Sabe qué es Bioincuba? Descubre cómo trabaja una incubadora de negocios en la universidad y las 10 ideas de negocio innovadoras.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 25', category: 'administracion', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota%20-%2025.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/en-que-consiste-carrera-administracion", "_self")'>¿En qué consiste la carrera de Administración?</h3><p>¿Te gustaría saber más información sobre  la carrera de Administración? Prepárate para contribuir en el éxito de empresas, organizaciones y emprendimientos.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 26', category: 'ambiental', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-26%20%281%29.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/de-que-trata-ingeniera-ambiental", "_self")'>¿De qué trata la ingeniería ambiental y su importancia?</h3><p>Descubre de qué trata la ingeniería ambiental, su importancia y las ramas en las que puedes especializarte.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 27', category: 'educacion', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-27.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/de-que-trata-carrera-educacion", "_self")'>¿De qué trata la carrera de Educación?: cursos y beneficios</h3><p>Entérate de qué trata la carrera de Educación, qué se estudia, sus beneficios y cómo puedes transformar el futuro siendo parte de esta profesión.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 28', category: 'estomatologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-28.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/que-es-estomatologia", "_self")'>¿Qué es la estomatología y por qué estudiar esta carrera? </h3><p>¿Aún no sabes qué es la estomatología? Descubre todo sobre esta carrera y cómo puedes contribuir al cuidado de la salud bucal</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 29', category: 'laboratorio', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-29.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/laboratorio-clinico-anatomia-patologica", "_self")'>Laboratorio Clínico y Anatomía Patológica: ¿En qué consiste?</h3><p>Conoce la importancia de la carrera de Tecnología Médica en Laboratorio Clínico y Anatomía Patológica y cuál es la mejor universidad para estudiarla.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 30', category: 'estomatologia', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-30.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/diferencia-entre-estomatologia-odontologia", "_self")'>Diferencia entre Estomatología y Odontología: ¿son lo mismo?</h3><p>¿Cuál es la diferencia entre Estomatología y Odontología? Descubre las diferencias clave, en qué se enfocan, y cuál elegir según tus necesidades.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 31', category: 'ambiental', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-31.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/que-cursos-lleva-ingenieria-ambiental", "_self")'>¿Qué cursos se lleva en ingeniería ambiental?</h3><p>Descubre los cursos de Ingeniería Ambiental, cuánto gana un profesional en Perú y por qué esta carrera es ideal para ti.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` },
    { name: 'Card 32', category: 'administracion', content: `<div class="bloque2DesktopCardsItem"><img src="https://upch-repo-comercial.s3.dualstack.us-east-1.amazonaws.com/06-03-25/Nota-32.webp" alt="Imagen de nota"><div class="content"><div class="sliderItemInfo6ItemInfoCalendar"><img src="https://blogs.cayetano.edu.pe/img/calendar-icon-whit.webp" alt=""><h3>11</h3><h3>|</h3><h3>03</h3></div><h3 onclick='window.open("https://blogs.cayetano.edu.pe/pregrado/importancia-carrera-administracion", "_self")'>Importancia de la carrera de administración</h3><p>Descubre  la importancia de la carrera de Administración y cómo puede abrirte muchas oportunidades. Conoce más sobre esta profesión y los beneficios de estudiarla.</p><img class="keyframe-button-movement" src="https://blogs.cayetano.edu.pe/img/arrow-black-button.webp" alt=""></div></div>` }
    // Añade más tarjetas según sea necesario
];

const cardsContainer = document.querySelector('.bloque2DesktopCards');
const filterSelect = document.getElementById('filter');
const paginationContainer = document.querySelector('.bloque2ProgramNotas');
const itemsPerPage = 6;
let currentPage = 1;

function renderCards(data) {
    cardsContainer.innerHTML = "";
    data.forEach((card) => {
      const cardDiv = document.createElement("div");
      cardDiv.classList.add("card");
      cardDiv.innerHTML = card.content;
      cardsContainer.appendChild(cardDiv);
    });
}

function renderPaginacion(totalPages) {
    paginationContainer.innerHTML = "";
    for (let i = 1; i <= totalPages; i++) {
        const pagina = document.createElement("button");
        pagina.textContent = i;
        pagina.classList.add("pagina");
        pagina.onclick = () => changePage(i);
        paginationContainer.appendChild(pagina);
    }
}

function changePage(page) {
    currentPage = page;
    const filteredData = filterSelect.value === "todos" ? cardsData : cardsData.filter((card) => card.category === filterSelect.value);
    const paginatedData = filteredData.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
    renderCards(paginatedData);
    const totalPages = Math.ceil(filteredData.length / itemsPerPage);
    renderPaginacion(totalPages);
}

filterSelect.addEventListener("change", () => {
    changePage(1);
});

changePage(1);

//- ======================================================================================================


const cardContainerMobile = document.querySelector('.bloque2Cards');
const filterSelectMobile = document.getElementById('filterMobile');
const paginationContainerMobile = document.querySelector('.bloque2ProgramNotasMobile');
const itemsPerPageMobile = 3;
let currentPageMobile = 1;

function renderCardsMobile(data) {
    cardContainerMobile.innerHTML = "";
    data.forEach((card) => {
      const cardDiv = document.createElement("div");
      cardDiv.classList.add("card");
      cardDiv.innerHTML = card.content;
      cardContainerMobile.appendChild(cardDiv);
    });
}

function renderPaginacionMobile(totalPages) {
    paginationContainerMobile.innerHTML = "";
    for (let i = 1; i <= totalPages; i++) {
        const pagina = document.createElement("button");
        pagina.textContent = i;
        pagina.classList.add("pagina");
        pagina.onclick = () => changePageMobile(i);
        paginationContainerMobile.appendChild(pagina);
    }
}

function changePageMobile(page) {
    currentPageMobile = page;
    const filteredDataMobile = filterSelectMobile.value === "todos" ? cardsData : cardsData.filter((card) => card.category === filterSelectMobile.value);
    const paginatedData = filteredDataMobile.slice((currentPageMobile - 1) * itemsPerPageMobile, currentPageMobile * itemsPerPageMobile);
    renderCardsMobile(paginatedData);
    const totalPages = Math.ceil(filteredDataMobile.length / itemsPerPageMobile);
    renderPaginacionMobile(totalPages);
}

filterSelectMobile.addEventListener("change", () => {
    changePageMobile(1);
});

changePageMobile(1);
